hyperparameters:
  aleatoric: true
  batch_size: 256
  dropout_prob: 0.6
  input_dim_fp: 128
  input_dim_gex: 867
  lr: 1.0181866635495813e-05
  max_epochs: 100
  mc_T: 50
  units_per_layer:
  - 512
  - 256
  - 128
  - 64
input_dim: 995
