hyperparameters:
  aleatoric: true
  dropout_prob: 0.2
  input_dim_fp: 128
  input_dim_gex: 867
  lr: 4.260914753081152e-05
  max_epochs: 100
  mc_T: 50
  units_per_layer:
  - 128
  - 64
  - 32
input_dim: 995
