hyperparameters:
  aleatoric: true
  batch_size: 256
  dropout_prob: 0.4
  input_dim_fp: 128
  input_dim_gex: 867
  lr: 1.7131815435286083e-05
  max_epochs: 100
  mc_T: 50
  units_per_layer:
  - 128
  - 64
  - 32
  - 32
input_dim: 995
